### ISSUE TITLE
Capitalize countries

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/hunger-games#386]
### What
- Capitalize countries

### Part of
- #37

**Comment by vedant-z** [comment]
@teolemon I just need some help.

Do I need to update the countries.json or other file?

**Comment by teolemon** [comment]
- It's currently here: https://github.com/openfoodfacts/hunger-games/blob/master/src/components/QuestionFilter/const.js#L12
- We also have this: https://github.com/openfoodfacts/hunger-games/blob/master/src/assets/countries.json

**Comment by alexfauquette** [comment]
For lazy people, capitalizing can also be done by using CSS 😇
https://developer.mozilla.org/en-US/docs/Web/CSS/text-transform

**Comment by vedant-z** [comment]
Even the most workaholic man on this planet will not be able to capitalise all the countries name manually @alexfauquette 

Thanks for helping 😊

**Comment by vedant-z** [comment]
I had one doubt though. Should I capitalise the id as well in json file, because the label is already capitalised.

**Comment by alexfauquette** [comment]
You should not touch to ids in any case, since they are the keys used to fetch the API. Modifying ids implies breaking API call

If we are talking about the country input in the question game filter, the options are defined as follow in `QuestionFilter.jsx`
```jsx
options={countryNames}
getOptionLabel={(countryTag) => countryTag.slice(3)}
```

For example when `countryTag="en:france"` it shows the option `"france"`.

Two solutions:
- Using https://github.com/openfoodfacts/hunger-games/blob/master/src/assets/countries.json to get a stardised name from the id
- Improve `(countryTag) => countryTag.slice(3)` such that it capitalize the name

**Comment by StarTrooper08** [comment]
Hey @teolemon, Is this issue still open?

Or is it solved?

I'm just getting started with contributing to Open Food Facts projects.
And I think this issue will be great for getting starting.

Please let me know if this issue is it still open to work on!?

**Comment by Sudhanva-Nadiger** [comment]
I solved the issue, if u need any help let me know @vedant-z

**Comment by alexfauquette** [comment]
@Sudhanva-Nadiger If you already fixed it feal free to open a PR

**Comment by Sudhanva-Nadiger** [comment]
Okay !! Will do that !!

**Comment by StarTrooper08** [comment]
I think this issue has PR merged and it can be closed now!!
