### ISSUE TITLE
Questions keeps loading forever

### ISSUE THREAD

**Issue by ayecptn** [openfoodfacts/hunger-games#573]
### What
The questions loading screen remains even though the API-call was successful.

### Steps to reproduce the behavior:
1. Login
2. Navigate to questions

### Expected behavior
Loading screen should disappear after the successful api-call. The weird thing is that the question-counter gets updated.

### Screenshots
![grafik](https://user-images.githubusercontent.com/61555365/224777123-5df9895a-f5f4-42e7-8afa-c8b54580ac74.png)

### Platform (Desktop, Mobile, Hunger Games)
 - OS: Desktop
 - Platform: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
 - Active Add-Ons: uBlock Origin.
 - Firefox privacy settings:
    - Block third-party cookies
    - Block fingerprinter
    -  Block krypto-miner

**Comment by Mount-Blanc** [comment]
I've been working on solving this bug for a while. I think i may have found something.

The two things that are relevant to this bug are the newQuestions array and the questionsToAdd array in the store.js located in the questions folder.

<img width="538" alt="Screen Shot 2023-06-24 at 2 14 43 PM" src="https://github.com/openfoodfacts/hunger-games/assets/102170589/7565940c-c231-4fe4-b727-1f6be85c9554">


**The issue**
The newQuestions array has objects from the api-about 23-25 each of which contains the barcode ,insight_id and so on. This is working as intended; the problem comes from the questionsToAdd array which collects only the objects which have the source_image_url key as seen below

**questionsToAdd array**

<img width="1353" alt="Screen Shot 2023-06-24 at 2 21 22 PM" src="https://github.com/openfoodfacts/hunger-games/assets/102170589/024ebee6-73be-488d-bc5a-f4773fd807ff">

Notice that this source_image_url key is missing in the objects in the newQuestions array

**newQuestions array** 

<img width="1355" alt="Screen Shot 2023-06-24 at 2 20 06 PM" src="https://github.com/openfoodfacts/hunger-games/assets/102170589/e97d1663-f42b-4ef5-bd12-1fd19d2e680c">

## Infinite loading Error

From what i have been able to see there are only about three objects which have the source_image_url key. The issue is this, the questionsToAdd array collects the only 3 objects which have the source_image_url key then later in the code there is a function that filters out the objects already collected. But since there is only three objects with the key it returns null and stays null. This null value is then passed to QuestionDisplay.jsx which has a function that runs the loading animation if the value of the question is null.

**QuestionsToAdd**
<img width="1366" alt="Screen Shot 2023-06-24 at 2 20 54 PM" src="https://github.com/openfoodfacts/hunger-games/assets/102170589/4e38bbfe-d47e-42ed-9a4d-2d523530edb7">

**QuestionDisplay.jsx**

<img width="650" alt="Screen Shot 2023-06-24 at 3 07 56 PM" src="https://github.com/openfoodfacts/hunger-games/assets/102170589/a3333b12-b6e8-48b5-b830-1212a1294135">

Conclusion
 The reason it is stuck in infinite loading is because most of the questions don't have the source_image_url key. A temporary fix i found is to delete the questionsToAdd variable completely and instead use the newQuestions variable in the rest of the program. Doing this solves the loading issue, but the major downside is that not every question has a cover image and some questions don't have any information at all.
